### ISSUE TITLE
selenium 경로 지정에 관한 오류 보고

### ISSUE THREAD

**Issue by Pyochangwoo** [ShowCreate/useful-information#1]
selenium_test.py 를 selenium 폴더 외부에 위치하게 하고 실행 했을떄 selenium 모듈을 불러오지 못하는 문제점이 있음

@ShowCreate

**Comment by ShowCreate** [comment]
selenium_test.py 파일을 selenium/common 폴더에 넣었을 때 정상적으로 작동합니다.
하지만, 근본적인 해결법은 아니기에 버그를 수정할 방법을 찾고 있는 중입니다. 
오류가 해결될 때까지 잠시 기다려주시길 바랍니다.

@Pyochangwoo

**Comment by ShowCreate** [comment]
셀레니움을 계속 고쳐봤는데, 원인을 찾았습니다. pip install로 부른 selenium과 현재 폴더 내에 있는 selenium이 이름이 같아서 그런 일이 벌어졌습니다. collect_information이라는 폴더에 selenium_test.py를 올려본 결과 잘 작동되는 것을 확인하였습니다. 그리고 현재 Firefox, Ie 브라우저만 정상 작동됩니다. Chrome과 Edge는 고쳐보도록 하겠습니다. 되도록이면 Firefox로 크롤링 하는 것을 목표로 해보겠습니다. 감사합니다.
@Pyochangwoo
